// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn5QFdFsIt1nncX1vGwvvXcKpUdnF8S9k',
    appId: '1:206459370390:web:87a712421849a78879bbb7',
    messagingSenderId: '206459370390',
    projectId: 'unsub-9b2dd',
    authDomain: 'unsub-9b2dd.firebaseapp.com',
    storageBucket: 'unsub-9b2dd.firebasestorage.app',
    measurementId: 'G-Z7HH44KEP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5bG49lfIFe17I0tEIRXXA6e9zYBJc_zE',
    appId: '1:206459370390:android:278b894e45a97c8479bbb7',
    messagingSenderId: '206459370390',
    projectId: 'unsub-9b2dd',
    storageBucket: 'unsub-9b2dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8JkQPAUGE4aZZu3fv1JyMaQ4mNmJD-tk',
    appId: '1:206459370390:ios:b877102eac19660179bbb7',
    messagingSenderId: '206459370390',
    projectId: 'unsub-9b2dd',
    storageBucket: 'unsub-9b2dd.firebasestorage.app',
    iosBundleId: 'com.karamlyy.unsub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8JkQPAUGE4aZZu3fv1JyMaQ4mNmJD-tk',
    appId: '1:206459370390:ios:b877102eac19660179bbb7',
    messagingSenderId: '206459370390',
    projectId: 'unsub-9b2dd',
    storageBucket: 'unsub-9b2dd.firebasestorage.app',
    iosBundleId: 'com.karamlyy.unsub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn5QFdFsIt1nncX1vGwvvXcKpUdnF8S9k',
    appId: '1:206459370390:web:4377ef848984ed1b79bbb7',
    messagingSenderId: '206459370390',
    projectId: 'unsub-9b2dd',
    authDomain: 'unsub-9b2dd.firebaseapp.com',
    storageBucket: 'unsub-9b2dd.firebasestorage.app',
    measurementId: 'G-MQV58J74X0',
  );
}
